[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'jistr/vim-nerdtree-tabs' 

[[plugins]]
repo = 'Xuyuanp/nerdtree-git-plugin'

[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'

# [[plugins]]
# repo = 'fatih/vim-go'

########## fzf coc ##########
[[plugins]]
repo = 'junegunn/fzf'
build_on = '''
./install -all
'''

[[plugins]]
repo = 'junegunn/fzf.vim'

[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'
on_i = 1
merged = '0'
hook_source = 'call coil398#init#coc#hook_source()'

##### A collection of language packs for #####
[[plugins]]
repo = 'sheerun/vim-polyglot'

##### editor color scheme #####
# [[plugins]]
# repo = 'wadackel/vim-dogrun'

# [[plugins]]
# repo = 'cocopon/iceberg.vim'

