[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'jistr/vim-nerdtree-tabs' 

[[plugins]]
repo = 'Xuyuanp/nerdtree-git-plugin'

[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'

########## fzf coc ##########
[[plugins]]
repo = 'junegunn/fzf'
build_on = '''
./install -all
'''

[[plugins]]
repo = 'junegunn/fzf.vim'

##### A collection of language packs for #####
[[plugins]]
repo = 'sheerun/vim-polyglot'

##### editor color scheme #####
# [[plugins]]
# repo = 'wadackel/vim-dogrun'

# [[plugins]]
# repo = 'cocopon/iceberg.vim'

